FROM ruby

USER root

RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    # Install node as the JS engine for uglifier
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /staytus
COPY Gemfile* ./
RUN bundle install --binstubs --without development test
COPY . ./

EXPOSE 5000
ENTRYPOINT ["/staytus/docker-start-dev.sh"]
