version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment: &env
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: staytus
      MYSQL_USER: staytus
      MYSQL_PASSWORD: staytus

  app:
    depends_on:
     - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /opt/staytus/docker-start-dev.sh
    ports:
      - 5000:5000
    volumes:
      - .:/staytus
    environment:
      <<: *env
      MYSQL_HOST: db

volumes:
  db_data: {}
